/**
 * Represents a credential object used to access a secure ArcGIS resource.
 * 
 * @module esri/identity/Credential
 * @since 4.0
 * @noconstructor        
 */

/**
 * Fires when the token associated with the credential is updated or changed.
 *
 * @event module:esri/identity/Credential#token-change
 */

/**
 * Fires when a credential object is destroyed. After the credential is 
 * destroyed, remove any map layers that use this credential.
 *
 * @event module:esri/identity/Credential#destroy
 */
define([
  "./IdentityManagerBase"
], function(
  IdentityManagerBase
) {

  var Credential = IdentityManagerBase.Credential;
    
  /**
   * @extends module:esri/core/Accessor
   * @constructor module:esri/identity/Credential
   * @param {Object} properties - See the [properties](#properties) for a list of all the properties
   *                            that may be passed into the constructor.
   */ 
    
  /////////////////////////////////////
  //
  // Properties
  //
  /////////////////////////////////////       
    
  /**
  * Token expiration time specified as number of milliseconds since 1 January 1970 00:00:00 UTC.
  *
  * @name expires
  * @type {number}
  * @instance
  * 
  * @see [Date - MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date)
  */
    
  /**
  * Indicates whether this credential belongs to a user with admin privileges. 
  *
  * @name isAdmin
  * @type {boolean}
  * @instance
  */  
    
  /**
  * The Identity Manager's 
  * {@link module:esri/identity/IdentityManager#setOAuthRedirectionHandler setOAuthRedirectionHandler} 
  * returns an object that contains a `state` property. This information is returned for this property. 
  *
  * @name oAuthState
  * @type {Object}
  * @instance
  */
    
  /**
  * The server url.
  *
  * @name server
  * @type {string}
  * @instance
  */
    
  /**
  * Indicates whether the resources accessed using this credential should be fetched over HTTPS protocol. 
  *
  * @name ssl
  * @type {boolean}
  * @instance
  */
    
  /**
  * Token generated by the token service using the specified userId and password.
  *
  * @name token
  * @type {string}
  * @instance
  */
    
  /**
  * User associated wth the Credential object.
  *
  * @name userId
  * @type {string}
  * @instance
  */    
    
  /////////////////////////////////////
  //
  // Methods
  //
  /////////////////////////////////////       
    
  /**
   * Destroys the credential. When the credential is destroyed, you should
   * remove any map layers that are using this credential.
   *
   * @method destroy
   * @memberOf module:esri/identity/Credential
   * @instance
   */   
    
  /**
   * Generates a new token and updates the Credential's [token](#token) property with 
   * the newly acquired token. Tokens are typically kept valid using a timer that automatically
   * triggers a refresh before the token expires. Use this method in cases where the 
   * timer has been delayed or stopped.
   *
   * @method refreshToken
   * @memberOf module:esri/identity/Credential
   * @instance
   */    

  // this is the public Credential class
  return Credential;
});
