define([
  "./esri/all",
  "./esri/core/all",
  "./esri/geometry/all",
  "./esri/identity/all",
  "./esri/layers/all",
  "./esri/symbols/all",
  "./esri/tasks/all",
  "./esri/views/all",
  "./esri/widgets/all",
  "./esri/request/request"
]);
