define([
  "./Accessor",
  "./Evented",
  "./HandleRegistry",
  "./JSONSupport",
  "./Loadable",
  "./Promise",
  "./lang",
  "./promiseList",
  "./domUtils",
  "./screenUtils",
  "./urlUtils",
  "./watchUtils"
]);
